siteName: Ashaz Autoz
tagline: Quality Cars, Premium Automotive Services
description: Your trusted automotive partner in Timor-Leste. Vehicle sales, imports, rentals, workshop, and premium automotive services.
url: https://ashazautoz.com
logo: /images/ashaz-logo.webp
favicon: /favicon.svg
phone:
  - +670 7715 4379
  - +670 7524 9000
  - +670 7379 7973
email: ashazautoz@gmail.com
address: Ponte Foun, Comoro, Dili, Timor-Leste
workingHours: Mon–Sat, 9:00–18:00
googleMapsEmbedUrl: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3945.3585290081387!2d125.52886647513672!3d-8.56148098683303!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2d01dd623160b801%3A0xe02d75cddc8c3237!2sAshaz%20Autos%20car%20sale!5e0!3m2!1sen!2sus!4v1782826726806!5m2!1sen!2sus
social:
  facebook: https://facebook.com/ashaz.autoz
  instagram: https://instagram.com/ashazautoz
  whatsapp: '+67077154379'
  tiktok: https://tiktok.com/@ashazautoztimorleste
lng: 125.52886647513672
currency: USD
lat: -8.56148098683303
languages:
  - en
  - tet
  - id
